export interface CitasTableModel {
    Expediente: string,
    TIPO_REGISTRO: string,
    CLAVE_LUGAR: string,
    ANIO: string,
    CONTROL: string,
    FCH_REG: Date,
    CRI: string,
    PATERNO: string,
    MATERNO: string,
    NOMBRE: string,
    EDAD: string,
    EDAD_APROX_ANIOS: number,
    EDAD_APROX_ANIOS_INI: number,
    EDAD_APROX_ANIOS_FIN: number,
    SEXO: string,
  }
  
  export interface CitasModel {
    TIPO_REGISTRO: string,
    CLAVE_LUGAR: string,
    ANIO: string,
    CONTROL: string,
    CRI: string,
    FECHA_INGRESO: Date,
    DESCONOCIDO: string,
    RESTOS_OSEOS: string,
    FECHA_IDENTIFICACION: Date,
    PATERNO: string,
    MATERNO: string,
    NOMBRE: string,
    ALIAS: string,
    SEXO: string,
    FECHA_NAC: Date,
    IDENTIFICACION_POR: string,
    EDAD_APROX_ANIOS: string,
    EDAD_APROX_MESES: string,
    EDAD_APROX_DIAS: string,
    NACIONALIDAD: number,
    EDAD_APROX_ANIOS_INI: number,
    EDAD_APROX_ANIOS_FIN: number,
    FCH_REG: Date,
    FCH_UAC: Date,
    USUARIO: string,
    OBSERVACIONES: string,
    PUBLICAR: Boolean
  }