export interface ExpedienteTableModel {
  Expediente: string,
  TIPO_REGISTRO: string,
  CLAVE_LUGAR: string,
  ANIO: string,
  CONTROL: string,
  FCH_REG: Date,
  CRI: string,
  PATERNO: string,
  MATERNO: string,
  NOMBRE: string,
  EDAD: string,
  EDAD_APROX_ANIOS: number,
  EDAD_APROX_ANIOS_INI: number,
  EDAD_APROX_ANIOS_FIN: number,
  SEXO: string,
}

export interface ExpedienteModel {
  CLAVE_LUGAR: string,
  ANIO: string,
  CONTROL: string,
  PATERNO: string,
  MATERNO: string,
  NOMBRE: string,
  SEXO: string,
  NO_EMPLEADO: string,
  PUESTO: string,
  TRAMITE: string,
  AREA_ADSCRIPCION: string,
  CELULAR: string,
  CORREO: string,
  VIGENCIA_C3: string,
  OFICIO_C3: string,
  FECHA_APERTURA: Date,
  FECHA_CITA: Date,
  OBSERVACIONES: string,
  USUARIO: string,
  FCH_REG: Date,
  FCH_UAC: Date
}
