export interface HuellasModel {
  TIPO_REGISTRO: string,
  CLAVE_LUGAR: string,
  ANIO: string,
  CONTROL: string,
  m1: string,
  m2: string,
  // d1: string,
  // d2: string,
  // d3: string,
  // d4: string,
  // d5: string,
  // d6: string,
  // d7: string,
  // d8: string,
  // d9: string,
  // d10: string,
  FCH_REG: Date,
  FCH_UAC: Date,
  USUARIO: string,
}
